### ISSUE TITLE
Vertical Slider does not work properly on touchscreens

### ISSUE THREAD

**Issue by gutiar-junky** [custom-cards/slider-button-card#44] opened 2023-02-01 06:56 UTC
**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser

**Release with the issue:**
1.10.10

**Last working release (if known):**

**Browser and Operating System:**
Chrome (latest) Dev with touch device emulation
Chrome on Android 12

**Description of problem:**
I can only use touch and slide, if i start the touch event on the slider but then move my finger beside it to change the value.
It is reproducable in the Chrome Dev tools when emulating a touch device.
I’ve mad a video here to showcase the issue:
https://static.n-hantke.de/slider-card-problem.mp4

(Also posted this at community.home-assistant.io)

**Javascript errors shown in the web inspector (if applicable):**
-

**Comment by coleek** [comment] 2023-04-10 02:03
+1 on HA app for iOS

**Comment by danleongjy** [comment] 2023-04-16 13:54
I was using @rohankapoorcom's fork at https://github.com/rohankapoorcom/slider-button-card until recently, and only ran into this issue when swapping out that version (1.10.7) for the latest (1.10.10) official HACS version. Reverting to 1.10.7 solved the issue for me.

**Comment by coleek** [comment] 2023-04-16 15:22
+1 on reverting versions— thank you!

Reverting back to 1.10.9 resolved the issue for me. Looks like maybe a resurfaced regression with v1.10.10…

**Comment by danleongjy** [comment] 2023-04-17 00:22
Confirmed that 1.10.9 does not have this issue. Looking at the changelog, it could be due to [this](https://github.com/custom-cards/slider-button-card/pull/28#issuecomment-1321934546)?

**Comment by rohankapoorcom** [comment] 2023-08-12 21:14
I think I've figured out how to fix this and pushed up a PR that should fix it (#54) while maintaining the functionality released in #28

**Closed** 2023-08-13 01:38 UTC
Labels: bug

**Comment by danleongjy** [comment] 2023-08-16 03:23
Thanks for the good work maintaining this card!  I have upgraded and it appears all good so far :)
